config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:show]
  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end
 
  resources :hikes do 
    resources :reviews
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.order_by_newest
    order("created_at DESC")
  end
end

app/models/hike.rb
class Hike < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
    belongs_to :user, optional: true
    validates :name, presence: true
    validates :summary, presence: true
    validates :location, presence: true
    validates :length, presence: true
    
    def self.search(search)
        if search
            where('name LIKE ?', "%#{search}%").order("created_at DESC")
        else
            order("created_at DESC")
        end
    end

    def self.import(data)
        trails = data["trails"].map do |hash|
            hike = Hike.new
            attributes = hash.select do |key, value|
                hike.respond_to?(key)
            end
            hike.update(attributes)
            hike
        end
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :hike
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
         has_many :hikes
         has_many :reviews
         has_many :reviewed_hikes, through: :reviews, source: :hike
         
         def self.new_with_session(params, session)
          super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
              user.email = data["email"] if user.email.blank?
            end
          end
        end
        
        def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
          end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticate_user!  
    
    def set_hike
        @hike = Hike.find(params[:hike_id])
    end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
    before_action :authenticate_user! 
 
    def index
        @hikes = Hike.search(params[:search])
    end

    def new
        @hike = Hike.new

    end
    
    def create
        if @hike = current_user.hikes.create(hike_params)
            redirect_to hikes_path
        else 
            render :new
        end
    end
    
    def show
        @hike = Hike.find(params[:id])
    end

    def edit
        @hike = Hike.find(params[:id])
    end

    def update
        @hike = Hike.find(params[:id])
        if @hike && @hike.user == current_user
            @hike.update(hike_params)
            redirect_to hikes_path
        else
            render :edit
        end
    end

    def destroy
        @hike = Hike.find(params[:id])
        if @hike && @hike.user == current_user
            @hike.destroy
            redirect_to hikes_path
        else 
            redirect_to @hike
        end
    end

    private

    def hike_params
        params.require(:hike).permit(:name, :summary, :location, :length,:img_url)
    end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_hike
    def index
        @reviews = set_hike.reviews.all
    end

    def new
        @review = set_hike.reviews.build

    end
    
    def create
        if current_user
            @review = set_hike.reviews.create(review_params)
            @review.user = current_user
            @review.save
        redirect_to hike_path(@hike)
        else
            render :new
        end
    end
    
    def show
        @review = set_hike.reviews.find(params[:id])
    end

    def edit
        @review = set_hike.reviews.find(params[:id])
    end

    def update
        @review = current_user.reviews.find(params[:id])
        @review.update(review_params)
        @review.save
        redirect_to hike_path(@hike)
    end

    def destroy
        current_user.review.destroy
        redirect_to reviews_path
    end

    private

    def review_params
        params.require(:review).permit(:content)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hikes/_form.erb
<% if @hike.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@hike.errors.count, "error") %> prohibited this hike from being saved:</h2>
 
    <ul>
    <% @hike.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@hike, class: "form-group") do |f| %>
    <%= f.label :name %>
    <%= f.text_area :name, class: "form-control", required: "required" %>
    <br>
    <%= f.label :summary %>
    <%= f.text_field :summary, class: "form-control", required: "required" %>
    <br>
    <br>
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control", required: "required" %>
    <br>
    <%= f.label :length %>
    <%= f.text_field :length, class: "form-control", required: "required" %>
    <br>
    <%= f.label :img_url %>
    <%= f.text_field :img_url, class: "form-control", required: "required" %>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/hikes/edit.erb
<h1>Edit Your Hike</h1>

    <%= render 'form' %>

app/views/hikes/index.erb
<h1 class="text-center display-4">Hikes</h1>
<br>
<br>
<a class= "btn btn-primary" href="hikes/new">Add Hike</a>
<br>
<br>
<%= form_tag(hikes_path, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag("Search") %>
<% end %>
<br>
<div class="container">
    <div class="row">
            <%@hikes.order_by_newest.each do |hike|%>
            <div class="col-lg-4 col-sm-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top, width: 700px, height: 400px" src="<%=hike.img_url%>" alt=""></a>
                    <div class="card-body">
                        <h5 class="card-title"><%=hike.name%></h5>
                    </div>
                    <a class="btn btn-info" href="/hikes/<%=hike.id%>">Show Hike</a>
                </div>
            </div>
            <%end%>
    </div>
</div>

app/views/hikes/new.erb
<h1>Add A Hike To The List</h1>

    <%= render 'form' %>

app/views/hikes/show.erb
<img class="card-img-top" style= "width: 60%" src="<%=@hike.img_url%>" alt=""></a>
                    <div class="card-body">
                        <h1 class="card-title"><%=@hike.name%></h1>
                        <p class="card-text"><strong>Summary:</strong><%=@hike.summary%></p>
                        <p class="card-text"><strong>Location:</strong><%=@hike.location%></p>
                        <p class="card-text"><strong>Length:</strong><%=@hike.length%>mi.</p>
                        <br>
                        <br>

                    
                        <%= button_to  "delete", @hike, method:"delete" %>
                
                        <br>
                        <a class="btn btn-warning" href=<%= edit_hike_path(@hike) %>>Edit Hike</a>
                        <h2>Reviews:</h2>
                            <%@hike.reviews.order_by_newest.each do |review|%>
                                <p class="card-text"><strong><%=review.user.email%> says:</strong> <%=review.content%></p>
                            <%end%>
                            <br>

                        <h1>Create Review</h1>
                            <%= link_to  "Write Your Review",  new_hike_review_path(@hike) %>
                    </div>

                    <a type="button" class="btn btn-default" href="/hikes">Back</a>

app/views/home/index.html.erb
<h1>Welcome <%= current_user.email%></h1>
<br>
<h2>Here are the hikes you have created</h2>
 <%current_user.hikes.order("created_at DESC").each do |hike|%>
            <div class="col-lg-4 col-sm-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top, width: 700px, height: 400px" src="<%=hike.img_url%>" alt=""></a>
                    <div class="card-body">
                        <h5 class="card-title"><%=hike.name%></h5>
                    </div>
                    <a class="btn btn-info" href="/hikes/<%=hike.id%>">Show Hike</a>
                </div>
            </div>
<%end%>

            <%
=begin%>
 <h3>Here are your reivews:</h3>
            <%current_user.reviews.order("created_at DESC").each do |review|%>
            <div class="col-lg-4 col-sm-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title"><%=review.content%></h5>
                    </div>
                    <%= link_to  "review.hike",  hike_review_path(review.hike) %>
                </div>
            </div> 
<%
=end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    
    <title>Hikt</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/stylesheets/main.css" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Hikt</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%# <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li> %>
        <li class="nav-item">
          <a class="nav-link" href="/hikes">Hikes</a>
          
        </li>
        <%
=begin%>
 <li>
            <a class="nav-link" href="/users/:id">Profile</a>
        </li> 
<%
=end%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/users/sign_in(">Log In</a>
            <a class="dropdown-item" href="/users/sign_up">Sign Up</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/users/edit">Edit Account</a>
            <a class="dropdown-item">  <%= link_to "Logout", destroy_user_session_path, method: :delete  %></a>
          </div>
        </li>
      </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>
  </nav>

  <div class="text-center">
    <div class="wrapper">
    
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <% unless current_user %> 
        <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <% else %>
        <%= current_user[:name] %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% end %>
      <br>
      <br>

      <%= yield %>
    </div>
  </div>
        

    <footer class="branding">
        <small>&copy; 2019 <strong>Hikt</strong></small>
    </footer>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>

app/views/reviews/_form.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@review.errors.count, "error") %>
      prohibited this review from being saved:
    </h2>
 
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([hike, review], class: "form-group") do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control", required: "required" %>
    <br>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/reviews/edit.erb
<%= render partial: "reviews/form", locals:{hike: @hike, review: @review} %>

app/views/reviews/new.erb
<%= render partial: "reviews/form", locals:{hike: @hike, review: @review} %>

app/views/reviews/show.erb
<h2><%= @hike.name%></h2>
<br>
<h3>Created by:<%=@review.user.email%></h3>
<br>
<p><%= @review.content%></p>
<br>
<%= button_to  "edit", @review, method:"patch" %>
<br>
<%= button_to  "delete", @review, method:"delete" %>